// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkSynSD0DIgWegLT7W_WsEw_ZyaElhYqo',
    appId: '1:974815699183:web:8a377096b43b9e952fbb1a',
    messagingSenderId: '974815699183',
    projectId: 'chat-app-8f488',
    authDomain: 'chat-app-8f488.firebaseapp.com',
    storageBucket: 'chat-app-8f488.appspot.com',
    measurementId: 'G-HD5S9LLR7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlExMBEtXyIwWFoFM9H9xCyId9vSlwwzw',
    appId: '1:974815699183:android:e34be67ce8a479a22fbb1a',
    messagingSenderId: '974815699183',
    projectId: 'chat-app-8f488',
    storageBucket: 'chat-app-8f488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnWbtCdaIbf6Y9Tj2Uxnrbfg3X-JSOO9A',
    appId: '1:974815699183:ios:eee8e3d5eb9a3ad62fbb1a',
    messagingSenderId: '974815699183',
    projectId: 'chat-app-8f488',
    storageBucket: 'chat-app-8f488.appspot.com',
    iosClientId: '974815699183-n9588pg3pskc2nsq8a9sao2un30mve4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnWbtCdaIbf6Y9Tj2Uxnrbfg3X-JSOO9A',
    appId: '1:974815699183:ios:eee8e3d5eb9a3ad62fbb1a',
    messagingSenderId: '974815699183',
    projectId: 'chat-app-8f488',
    storageBucket: 'chat-app-8f488.appspot.com',
    iosClientId: '974815699183-n9588pg3pskc2nsq8a9sao2un30mve4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
